name = "PyDraw"
uuid = "fce23259-28de-47d5-8db8-ab4b90e0411e"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de> and contributors"]
version = "0.0.2"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
julia = "1.6"
